import type { PublicConfig } from "../config/publicConfig";
import { publicPolicyDefaults } from "../config/publicConfig";

export type PublicLanguage = "zh-Hant" | "en";
export const escapeHtml = (value: string): string => value.replace(/[&<>"']/g,
  (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
export const publicLanguage = (query: URLSearchParams, accepted = ""): PublicLanguage => {
  const explicit = query.get("lang");
  if (explicit === "en" || explicit === "zh-Hant") return explicit;
  const languages = accepted.split(",").map((entry, index) => {
    const [tag, ...parameters] = entry.trim().split(";");
    const qualityText = parameters.find((parameter) => parameter.trim().startsWith("q="))?.trim().slice(2);
    const quality = qualityText === undefined ? 1 : Number(qualityText);
    return { tag: tag.toLowerCase(), quality, index };
  }).filter(({ tag, quality }) => /^(en|zh)(-|$)/.test(tag) && Number.isFinite(quality) && quality > 0 && quality <= 1)
    .sort((a, b) => b.quality - a.quality || a.index - b.index);
  return languages[0]?.tag.startsWith("en") ? "en" : "zh-Hant";
};
export interface PageServicePolicy {
  servicePolicyVersion: string; mailEnabled?: boolean; registrationEnabled?: boolean;
  ai: { displayName: string; dataRecipients: string[]; dataTerms: string; };
}
export const policyContent = (kind: "privacy" | "support", language: PublicLanguage, config: PublicConfig, policy?: PageServicePolicy): string => {
  const en = language === "en";
  const t = (zh: string, english: string) => en ? english : zh;
  const e = escapeHtml;
  const section = (zh: string, english: string, textZh: string, textEn: string) => `<section><h2>${t(zh, english)}</h2><p>${t(textZh, textEn)}</p></section>`;
  const contact = `<a href="mailto:${e(config.supportEmail)}">${e(config.supportEmail)}</a>`;
  const metadata = `<dl class="metadata"><div><dt>${t("營運者", "Operator")}</dt><dd>${e(config.operator)}</dd></div><div><dt>${t("聯絡方式", "Contact")}</dt><dd>${contact}</dd></div>${kind === "privacy" ? `<div><dt>${t("政策版本", "Policy version")}</dt><dd>${e(config.policyVersion)}</dd></div>` : ""}</dl>`;
  const mail = policy?.mailEnabled === true;
  if (kind === "support") return `<p class="lead">${t("帳號、資料或使用上的問題，都可以從這裡找到下一步。", "Find the next step for account, data or app questions.")}</p>${metadata}`
    + section("登入與帳號", "Sign in and accounts", mail
      ? "使用 Email 與密碼註冊或登入。此部署啟用寄信，帳號需完成 Email 驗證；只有已驗證的 Email 可接收密碼重設信；未驗證 Email 不作為帳號恢復的唯一依據。驗證與重設連結有效 30 分鐘，重新申請後請使用最新信件。"
      : "此部署未啟用寄信；可用 Email 與密碼註冊及登入，Email 僅作為帳號識別，不代表信箱所有權已驗證。請確認地址並妥善保存密碼。無法寄送驗證、密碼重設或新的監護人確認／撤回連結；若忘記密碼，可聯絡客服提出問題，但目前未提供保證可用的人工帳號恢復流程。", mail
      ? "Register or sign in with an email address and password. Email delivery is enabled here and email verification is required. Password reset emails are sent only to verified addresses; an unverified address is not sufficient for account recovery. Verification and password reset links last 30 minutes; use the latest email after requesting another link."
      : "Email delivery is disabled here. You can register and sign in with an email address and password. The address is an account identifier, not proof of mailbox ownership. Check it carefully and keep your password safe. Verification, password reset and new guardian confirmation or withdrawal emails cannot be sent. You may contact support if you forget your password, but a reliable manual account recovery process is not currently provided.")
    + section("年齡與監護人", "Age and guardian approval", "臺灣正式帳號限 15 歲以上；15–17 歲仍需獨立監護人同意。寄信未啟用且尚無有效同意時，不能新增正式資料或使用外部 AI；仍可查看、匯出、刪除自己的既有資料及使用合成資料訪客體驗。家庭邀請不能取代監護人同意。", "Formal accounts in Taiwan are for ages 15 and up. Ages 15–17 still need separate guardian approval. If email is disabled and no valid approval exists, new formal data entry and external AI are blocked. You can still view, export or delete your existing data and try guest mode with synthetic data. A family invitation does not replace guardian approval.")
    + section("匯出與刪除帳號", "Export and delete your account", "在 App 設定可匯出自己的 JSON 資料；刪除帳號時需輸入目前密碼並再次確認。刪除會移除使用中資料庫的帳號及個人資料，並解除家庭關聯；家長刪除帳號會解散其家庭。若無法登入，可聯絡客服提出資料權利請求；客服仍需確認身分，不保證僅憑 Email 即可恢復或刪除帳號。保存及刪除 journal 說明見隱私權政策。", "Export your own data as JSON in app settings. To delete your account, enter your current password and confirm again. Deletion removes your account and personal data from the active database and ends family membership; deleting a parent account dissolves that family. If you cannot sign in, contact support with a data rights request. Identity checks are still needed; email alone does not guarantee recovery or deletion. See the privacy policy for retention and the deletion journal.")
    + section("提供問題資訊", "Describe the issue", "請提供 App 版本、裝置／系統版本、發生步驟及已遮蔽個資的錯誤畫面。請勿寄送密碼、驗證連結、完整帳務或他人資料。AI 不是即時投資或金融服務；手動記帳與固定教材可在未啟用 AI 時使用。", "Include the app version, device and OS version, steps to reproduce and an error screenshot with personal information hidden. Do not send passwords, verification links, complete financial records or other people’s data. AI is not a live investment or financial service. Manual records and fixed learning materials remain available without AI.");
  const backup = config.backupRetentionDays > 0
    ? t(`此部署設定備份保留 ${config.backupRetentionDays} 天；實際備份排程、儲存與銷毀由營運者管理。`, `This deployment configures ${config.backupRetentionDays} days of backup retention; the operator manages the actual backup schedule, storage and destruction.`)
    : t("此部署不建立定期資料庫備份；此設定不會刪除既有備份副本。", "This deployment does not create scheduled database backups. This setting does not delete existing backup copies.");
  const disclosure = (value: string, defaultKey: string, english: string) => en && value === publicPolicyDefaults[defaultKey]
    ? english : e(value);
  return `<p class="lead">${t("了解 FutureMint AI 使用哪些資料，以及你可以做的選擇。", "Understand the data FutureMint AI uses and the choices you have.")}</p>${metadata}`
    + section("資料與用途", "Data and purposes", "帳號保存 Email、加鹽雜湊密碼、驗證狀態與登入工作階段；並保存你提供的年齡分組、服務／AI 同意狀態、監護人 Email 與確認狀態。你主動保存的預算、目標、收入支出、訂閱合約、學習進度、虛擬投資訂單與家庭關聯，用於提供記帳、教育與分享功能。訂閱合約不代表實際扣款。", "Accounts store email addresses, salted password hashes, verification status and login sessions, plus your declared age band, service and AI consent, guardian email and approval status. Budgets, goals, income and spending records, subscription contracts, learning progress, virtual investment orders and family links that you save support record keeping, education and sharing. A subscription contract does not represent an actual payment.")
    + section("Email 與可選寄信", "Email and optional delivery", mail
      ? "此部署啟用寄信；Email 用於帳號識別、信箱驗證與密碼重設；只有已驗證的 Email 可接收密碼重設信，未驗證地址不作為客服或帳號恢復的唯一依據。監護人申請會將使用者帳號 Email 寄給指定監護人以辨識申請，並處理同意／撤回連結。寄信需要透過營運者設定的 SMTP 服務處理收件地址及信件內容。"
      : "此部署未啟用寄信；Email 僅作為帳號識別，可用於註冊及登入，不代表信箱所有權已驗證。沒有新的驗證、密碼重設或監護人確認／撤回信件，也不保證人工恢復帳號。停用寄信不會自動改寫既有驗證或監護人同意狀態。", mail
      ? "Email delivery is enabled here. Email is used for account identification, mailbox verification and password resets. Only verified addresses can receive password reset emails; unverified addresses alone are insufficient for support identity checks or account recovery. Guardian requests include the account email so the designated guardian can identify the requester, and use confirmation or withdrawal links. Delivery processes recipient addresses and email content through the SMTP service configured by the operator."
      : "Email delivery is disabled here. Email serves as an account identifier for registration and sign in, not proof of mailbox ownership. No new verification, password reset or guardian confirmation or withdrawal emails are sent. Manual account recovery is not guaranteed. Disabling mail does not automatically change existing verification or guardian approval records.")
    + section("選擇使用第三方 AI", "Optional third-party AI", "啟用前需另外同意當前供應商、模型與資料條款，系統不自動切換供應商。文字解析傳送本次文字、語系與參考時間；微課選題傳送近期分類與目標是否存在；學習規劃傳送帳號角色、分類、目標／訂閱／不確定消費是否存在；陪讀傳送問題與主題。解析原文不保存於資料庫或一般應用紀錄；請勿輸入姓名、聯絡方式或他人資料。模型選擇受控教材主題，數值由程式計算。", "Separate consent to the current provider, model and terms is required before use; providers are not switched automatically. Parsing sends the current text, language and reference time. Lesson selection sends recent categories and whether a goal exists. Learning plans send the account role, categories and whether goals, subscriptions or uncertain spending exist. Coaching sends your question and topic. Parsing text is not saved to the database or ordinary application logs. Do not enter names, contact details or others’ data. Models select topics from controlled materials; code calculates numeric results.")
    + `<div class="notice"><h3>${t("目前部署的 AI 說明", "AI declaration for this deployment")}</h3><p>${t("供應商", "Provider")}: ${e(policy?.ai.displayName ?? t("未提供", "Not provided"))}</p><p>${t("資料接收者", "Data recipients")}: ${e(policy?.ai.dataRecipients.join(", ") || t("無已揭露的第三方接收者", "No declared third-party recipients"))}</p><p class="declaration">${e(policy?.ai.dataTerms || t("供應商資料說明尚未完成；外部 AI 不可啟用。", "Provider terms are incomplete; external AI cannot be enabled."))}</p><p>${disclosure(config.aiDataTerms, "AI_DATA_TERMS_DISCLOSURE", "Third-party AI needs separate consent. Parsing sends the current input; education uses necessary categories and questions. Declining or withdrawing consent preserves manual records, subscription management and fixed learning materials. Recipients and processing terms are shown here and on the app consent screen.")}</p><p>${t("接收方與條款依營運者確認的原文呈現，可能使用其他語言；不另外推定保存期限、訓練、地區或上游承諾。未確認說明時外部 AI 保持停用。", "Recipients and terms are shown exactly as reviewed by the operator and may be in another language. No additional retention, training, region or upstream promises are inferred. External AI stays disabled if its declaration is not reviewed.")}</p></div>`
    + section("年齡與監護人", "Age and guardian approval", `臺灣正式服務限 15 歲以上；未滿 15 歲僅提供合成資料訪客體驗。15–17 歲需獨立監護人同意；Email 控制權與身分聲明不證明法定代理人身分。申請寄信未啟用且沒有有效同意時，不能新增正式資料或使用外部 AI，但可查看、匯出及刪除既有資料。${e(config.minorConsent)}`, `Formal service in Taiwan is for ages 15 and up; under 15s may only use guest mode with synthetic data. Ages 15–17 need separate guardian approval. Mailbox access and identity declarations do not prove legal guardianship. Without enabled approval emails or valid existing consent, new formal data entry and external AI are blocked, while viewing, exporting and deleting existing data remain available. ${disclosure(config.minorConsent, "MINOR_CONSENT_DISCLOSURE", "Service eligibility, family summary sharing and AI consent are separate choices.")}`)
    + section("家庭摘要分享", "Family summary sharing", "孩子選擇加入家庭後，家長可查看預算、收入／支出／訂閱彙總、可用金額、目標進度、提醒數量及教學摘要；不取得逐筆交易、原文、Email 或投資訂單。孩子可離開家庭停止後續分享，家長可更新或停用 24 小時有效的邀請碼。家庭角色與邀請不是監護人同意，也不會啟用 AI。", "When a child chooses to join a family, the parent can view budget, income, spending and subscription totals, available money, goal progress, reminder counts and learning summaries. The parent does not receive individual transactions, original input, email or investment orders. A child can leave to stop future sharing. Parents can renew or disable invitations, which expire after 24 hours. Family roles and invitations are not guardian approval and do not enable AI.")
    + section("儲存與保存", "Storage and retention", `資料存放地區：${e(config.dataRegion)}。帳號及業務資料保存至刪除帳號。${backup}登入憑證 7 天到期，登出會撤銷該工作階段；到期／撤銷憑證、一次性連結與限流資料由定期維護分批清除，過期即不能使用。`, `Data region: ${e(config.dataRegion)}. Account and business data remain until account deletion. ${backup} Sessions expire after 7 days and signing out revokes the current session. Maintenance clears expired or revoked sessions, one-time links and rate-limit records in batches; expiry blocks use immediately.`)
    + section("刪除與最小刪除紀錄", "Deletion and the minimal journal", "App 內刪除需目前密碼及再次確認；使用中資料庫移除帳號、個人資料、家庭關聯與工作階段。另保留帳號 ID 的 SHA-256 雜湊及刪除時間，不含 Email、帳務、密碼或 token，用於舊備份還原對帳；程式沒有自動清除這份紀錄。營運者須確認所有早於刪除的備份副本已銷毀，再依保留政策清理；備份設定為 0 不會立即清除 journal。", "In-app deletion requires your current password and confirmation. The active database removes the account, personal data, family links and sessions. A separate journal keeps the SHA-256 hash of the account ID and deletion time for reconciliation after older backups are restored. It contains no email, financial records, password or token and is not automatically purged by the program. The operator must confirm destruction of every pre-deletion backup before clearing it under the retention policy. Setting backups to 0 does not immediately remove this journal.")
    + section("裝置、訪客與網頁儲存", "Devices, guests and web storage", "原生 App 憑證與待確認操作使用系統安全儲存；Web 使用瀏覽器本機儲存。登出／到期清除憑證，但帳號分隔的待確認訂閱／虛擬訂單保留供同帳號重新登入核對；App 內刪除帳號時清除。訪客理財資料僅在記憶體，關閉、重新整理或切換帳號後清除。iPhone 本機提醒由你授權，不使用遠端推播，通知不含金額、訂閱名稱或帳務；登出、刪除及切換帳號清除提醒，其他裝置變動需回 App 同步。公開政策／支援頁不設定 cookies、不使用追蹤程式，也不載入第三方字型或資源；語言與主題選擇僅在網址參數。", "Native apps use system secure storage for credentials and pending operations; the web app uses browser local storage. Sign out and expiry clear credentials, while account-separated pending subscriptions or virtual orders remain for reconciliation on the same account’s next sign in; in-app account deletion clears them. Guest financial data exists only in memory and disappears on close, refresh or account switch. Optional iPhone reminders are scheduled locally without remote push and contain no amounts, subscription names or financial records. Sign out, deletion and account switches clear reminders; changes on other devices require an app sync. Public privacy and support pages set no cookies, run no trackers and load no third-party fonts or assets. Language and theme choices exist only in URL parameters.")
    + section("連線、安全與紀錄", "Connections, security and logs", "正式連線應使用 HTTPS。後端驗證帳號及資料權限，密碼加鹽雜湊、登入及一次性連結僅保存 token 雜湊。API 會處理來源 IP 做限流，限流識別值以雜湊保存；應用請求紀錄可能含 IP、路徑、時間、請求 ID 與結果。反向代理及代管平台也可能記錄連線資訊；其存取與保存期限需由營運者管理，不宣稱紀錄完全匿名或零保存。請勿將秘密或個資放在 URL。", "Production connections should use HTTPS. The backend checks account and data permissions, salts password hashes and stores only hashes of session and one-time tokens. The API processes source IPs for rate limiting and stores hashed rate-limit identifiers. Request logs may include IP addresses, paths, times, request IDs and outcomes. Reverse proxies and hosting platforms may also log connections; the operator manages access and retention. These logs are not claimed to be fully anonymous or never retained. Do not put secrets or personal information in URLs.")
    + section("你的選擇與權利", "Your choices and rights", "在 App 可查看、修改、匯出自己的 JSON 資料及刪除帳號；匯出不含密碼、token 或其他家庭成員明細。可撤回 AI 或監護人同意，停止新的相關請求；已開始的請求仍可能完成。拒絕 AI 不影響合資格帳號手動記帳與固定教材；未完成監護人同意仍可讀取、匯出、刪除既有資料。其他查詢、更正、停止使用或刪除請求請聯絡客服，需核對身分及可執行範圍。", "In the app you can view, edit, export your own JSON data and delete your account. Exports omit passwords, tokens and other family members’ details. Withdraw AI or guardian consent to block new related requests; requests already started may complete. Declining AI preserves manual records and fixed materials for eligible accounts. Without guardian approval you can still read, export or delete existing data. Contact support for other access, correction, restriction or deletion requests; identity and the available action must be checked.")
    + section("服務範圍與政策更新", "Service scope and policy updates", "不使用廣告追蹤，不串接銀行、支付、電子發票或真實證券交易。教育試算與虛擬訂單不是即時投資建議或報酬保證。公開政策以本頁版本為準；供應商、模型或資料條款改變時，外部 AI 需重新同意。此說明與程式中的同意流程不代表所有法律或未成年人營運條件已完成查核；疑問請聯絡上述營運者。", "There is no advertising tracking, bank, payment, invoice or live securities trading integration. Educational scenarios and virtual orders are not live investment advice or guaranteed returns. This page identifies the current privacy version; changes to AI providers, models or terms require new AI consent. This notice and in-app consent do not certify completion of all legal or minor-service operating requirements. Contact the operator above with questions.");
};
